### PR TITLE
Add move to github script.

### PR DESCRIPTION
**Pull request by daspecster**

### CODE REVIEW

**Comment by MichaelCastelbuono** [comment]
Looks good @daspecster — My bash knowledge is lacking, but it looks good, plus your use of it worked nicely 👍

**Comment by daspecster** [comment]
Thanks @MichaelCastelbuono!

**Comment by austinkregel** [comment]
:-1: I think it lacks some error checking in case the user doesn't pass through the desired arguments. Other than that it looks good :)

**Comment by austinkregel** [comment]
One function I use to "validate" bash input is something like the following

```bash
#!/bin/bash

set -e

USAGE="Usage ./script.sh {origin-repo-branch} {new-repo-url}"

validateInput() {
    if [ -z "$1" ]; then
        echo ""
        echo $2;
        echo $USAGE
        exit 1;
    fi
}

ORIGIN=$1
NEWREPO=$2

validateInput "$ORIGIN" "You must enter the origin repository's branch name"
validateInput "$NEWREPO" "You must enter the URL to the new repository"

# Rest of script logic here...
```

**Comment by daspecster** [comment]
@austinkregel PR! ;)

**Pull request merged**
